-- MySQL Script generated by MySQL Workbench
-- Tue May 10 12:39:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TIP_PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIP_PAGO` (
  `id_tip_pago` INT NOT NULL AUTO_INCREMENT,
  `pag_tip_pag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tip_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DET_VENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DET_VENT` (
  `id_det_vent` INT NOT NULL AUTO_INCREMENT,
  `produc_det` VARCHAR(150) NOT NULL,
  `user_det` VARCHAR(45) NOT NULL,
  `hora_det` VARCHAR(5) NOT NULL,
  `fecha_det` VARCHAR(20) NOT NULL,
  `TIP_PAGO_id_tip_pago` INT NOT NULL,
  PRIMARY KEY (`id_det_vent`),
  INDEX `fk_DET_VENT_TIP_PAGO1_idx` (`TIP_PAGO_id_tip_pago` ASC) VISIBLE,
  CONSTRAINT `fk_DET_VENT_TIP_PAGO1`
    FOREIGN KEY (`TIP_PAGO_id_tip_pago`)
    REFERENCES `mydb`.`TIP_PAGO` (`id_tip_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTAS` (
  `id_vent` INT NOT NULL AUTO_INCREMENT,
  `produc_id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `DET_VENT_id_det_vent` INT NOT NULL,
  PRIMARY KEY (`id_vent`),
  INDEX `fk_VENTAS_DET_VENT_idx` (`DET_VENT_id_det_vent` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_DET_VENT`
    FOREIGN KEY (`DET_VENT_id_det_vent`)
    REFERENCES `mydb`.`DET_VENT` (`id_det_vent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
